### PR TITLE
[Module/PR/Python] Fix bugs in the pr-format-pylint script

### LINKED ISSUE #476: [Module] pr-format-pylint seems not work well
# Issue Description
While I am reading the report generated by the ci for my PR, I found something wrong in the pylint module.

Please look into the following code snippets from pr-format-pylint.sh.

```bash 
    if [[ `file $i | grep "ASCII text" | wc -l` -gt 0 ]]; then
        # in case of source code files: *.py)
        case $i in
            # in case of python code
            *.py)
                echo "[DEBUG] ( $i ) file is source code with the text format."
                py_analysis_sw="pylint"
                py_analysis_rules=" --reports=y "
                py_check_result="pylint_result.txt"
```
- line 51: Check C/C++ file -> Check python file
```bash
                # Check C/C++ file, enable all checks.
```
```bash
                if [[ ! -e ~/.pylintrc ]]; then
                    $py_analysis_sw --generate-rcfile > ~/.pylintrc
                fi
                $py_analysis_sw $py_analysis_rules  > ../report/${py_check_result}
```
- line 56: $cppcheck_result -> $py_check_result
  -  In addition, IMO, `wc -l $cppcheck_result` will print out the result like "$NUM $FILENAME" thus                 'if  [[ $line_count -lt 0 ]]; then' may not work as well.
```bash
                line_count=`wc -l $cppcheck_result`

                # TODO: apply strict rule with pass/failure instead of report when developers understand investigation result of pylint.
```
- line 58: -lt -> -gt ?
```bash
                if  [[ $line_count -lt 0 ]]; then
                    echo "[DEBUG] $py_analysis_sw: failed. file name: $i, There are $line_count bug(s)."
                    check_result="failure"
                    global_check_result="failure"
                    break
                else
                    echo "[DEBUG] $py_analysis_sw: passed. file name: $i, There are $line_count bug(s)."
                    check_result="success"
                fi
                ;;
            * )
                echo "[DEBUG] ( $i ) file can not be investigated by pylint (statid code analysis tool)."
                check_result="skip"
                ;;
        esac
    fi
```

### PR DESCRIPTION
**Pull request by wooksong**
This PR fixes several bugs related to https://github.com/nnsuite/TAOS-CI/issues/476

**Self evaluation:**
1. Build test: [ ]Passed [ ]Failed [*]Skipped
2. Run test: [ ]Passed [ ]Failed [* ]Skipped

Note that run-test was done in the local environment only.

Resolves #476 

Signed-off-by: Wook Song <wook16.song@samsung.com>

### CODE REVIEW

File: ci/taos/plugins-good/pr-format-pylint.sh [hunk 1]
```diff
@@ -48,14 +48,20 @@ for i in ${FILELIST}; do
...
-                # Check C/C++ file, enable all checks.
+
                 if [[ ! -e ~/.pylintrc ]]; then
                     $py_analysis_sw --generate-rcfile > ~/.pylintrc
                 fi
-                $py_analysis_sw $py_analysis_rules  > ../report/${py_check_result}
-                line_count=`wc -l $cppcheck_result`
+
+                # Check Python files
+                $py_analysis_sw $py_analysis_rules $i > ../report/${py_check_result}
```
Comment (leemgs) [inline ci/taos/plugins-good/pr-format-pylint.sh]: 👍

File: ci/taos/plugins-good/pr-format-pylint.sh [hunk 2]
```diff
@@ -48,14 +48,20 @@ for i in ${FILELIST}; do
...
+                line_count=$((`cat $py_check_result | grep W: | wc -l` + \
+                    `cat $py_check_result | grep C: | wc -l` + \
+                    `cat $py_check_result | grep E: | wc -l` + \
+                    `cat $py_check_result | grep R: | wc -l`))
+
                 # TODO: apply strict rule with pass/failure instead of report when developers understand investigation result of pylint.
-                if  [[ $line_count -lt 0 ]]; then
+                if  [[ $line_count -gt 0 ]]; then
```
Comment (leemgs) [inline ci/taos/plugins-good/pr-format-pylint.sh]: Nice catch.
